#!/usr/bin/env bash

IN_FILE="${1}"
#BITRATE=$(ffprobe -v quiet -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1:nokey=1 "${IN_FILE}")
BITRATE=$(( $(ffprobe -v quiet -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1:nokey=1 "${IN_FILE}") / 2 ))
TMP_FILE="${RANDOM}.mkv"
#OUT_FILE="$(basename ${IN_FILE} .mp4 | sed -e 's/h264m/h265m/').mkv"
OUT_FILE="$(basename ${IN_FILE} .mp4)"
#OUT_FILE="${OUT_FILE}-yts.mkv"
OUT_FILE="${OUT_FILE}-nvenc.mkv"

convert_yts() 
{
	ffmpeg -y -i "${IN_FILE}" \
		-c:v libx264 \
		-crf 27 \
		-x264-params cabac=1:ref=5:analyse=0x133:me=umh:subme=9:chroma-me=1:deadzone-inter=21:deadzone-intra=11:b-adapt=2:rc-lookahead=60:vbv-maxrate=10000:vbv-bufsize=10000:qpmax=69:bframes=5:b-adapt=2:direct=auto:crf-max=51:weightp=2:merange=24:chroma-qp-offset=-1:sync-lookahead=2:psy-rd=1.00,0.15:trellis=2:min-keyint=23:partitions=all \
		-c:a aac \
		-ar 44100 \
		-b:a 128k \
		-map 0 \
		"${TMP_FILE}"
}

convert_hevc() 
{
	ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda \
		-i "${IN_FILE}" \
		-c:v hevc_nvenc \
		-vtag hvc1 \
		-preset slow \
		-b:v ${BITRATE} \
		-maxrate ${BITRATE} \
		-bufsize ${BITRATE} \
		-c:a copy \
		"${TMP_FILE}"
}

remove-tmp() 
{
	if [ -f "${TMP_FILE}" ]; then
		rm "${TMP_FILE}"
	fi
}

trap remove-tmp EXIT

if [[ ! -f "${OUT_FILE}" ]]; then
	convert_hevc "${IN_FILE}"

	if [ $? -eq 0 ]; then
		mv "${TMP_FILE}" "${OUT_FILE}"
	fi
fi

