#!/usr/bin/env bash

IN_FILE="${1}"
#BITRATE=$(ffprobe -v quiet -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1:nokey=1 "${IN_FILE}")
BITRATE=$(( $(ffprobe -v quiet -select_streams v:0 -show_entries stream=bit_rate -of default=noprint_wrappers=1:nokey=1 "${IN_FILE}") / 2 ))

OUT_FILE="$(basename ${IN_FILE} .mp4 | sed -e 's/h264m/h265m/').mkv"

convert() {
	ffmpeg -hwaccel cuda -hwaccel_output_format cuda \
		-i "${IN_FILE}" \
		-c:v hevc_nvenc \
		-vtag hvc1 \
		-preset slow \
		-b:v ${BITRATE} \
		-maxrate ${BITRATE} \
		-bufsize ${BITRATE} \
		-c:a copy \
		"${OUT_FILE}"
}

if [[ ! -f "${OUT_FILE}" ]]; then
	convert "${IN_FILE}"
fi

